"""baseline: full domain schema

Revision ID: 864543ca2597
Revises: 
Create Date: 2026-09-08 16:58:34.447128
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '864543ca2597'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('subject_type', sa.String(length=30), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_subject_type'), 'audit_log', ['subject_type'], unique=False)
    op.create_table('catalogue_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('region_code', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('category_path', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_attribution', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalogue_items')),
    sa.UniqueConstraint('region_code', 'code', name='uq_catalogue_region_code')
    )
    op.create_index(op.f('ix_catalogue_items_region_code'), 'catalogue_items', ['region_code'], unique=False)
    op.create_table('evidence_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('ref', sa.String(length=1024), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_links'))
    )
    op.create_index(op.f('ix_evidence_links_subject_id'), 'evidence_links', ['subject_id'], unique=False)
    op.create_index('ix_evidence_subject', 'evidence_links', ['subject_type', 'subject_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued','running','succeeded','failed','cancelled')", name=op.f('ck_jobs_job_status_ck')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('region_code', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_projects_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('catalogue_item_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entered_by', sa.Uuid(), nullable=True),
    sa.Column('imported_from', sa.String(length=512), nullable=True),
    sa.CheckConstraint("scope IN ('default','project','vendor')", name=op.f('ck_rates_rate_scope_ck')),
    sa.CheckConstraint('amount_minor >= 0', name=op.f('ck_rates_rate_nonneg_ck')),
    sa.ForeignKeyConstraint(['catalogue_item_id'], ['catalogue_items.id'], name=op.f('fk_rates_catalogue_item_id_catalogue_items')),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], name=op.f('fk_rates_entered_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rates'))
    )
    op.create_index(op.f('ix_rates_catalogue_item_id'), 'rates', ['catalogue_item_id'], unique=False)
    op.create_table('drawing_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_drawing_files_project_id_projects')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_drawing_files_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drawing_files'))
    )
    op.create_index(op.f('ix_drawing_files_project_id'), 'drawing_files', ['project_id'], unique=False)
    op.create_index(op.f('ix_drawing_files_sha256'), 'drawing_files', ['sha256'], unique=False)
    op.create_table('measurement_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_measurement_runs_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measurement_runs'))
    )
    op.create_index(op.f('ix_measurement_runs_project_id'), 'measurement_runs', ['project_id'], unique=False)
    op.create_table('storeys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('elevation_mm', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_storeys_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storeys'))
    )
    op.create_table('ai_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('subject_type', sa.String(length=30), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('suggestion_type', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('prompt_log_id', sa.Uuid(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_ai_suggestions_ai_conf_ck')),
    sa.ForeignKeyConstraint(['run_id'], ['measurement_runs.id'], name=op.f('fk_ai_suggestions_run_id_measurement_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_suggestions'))
    )
    op.create_index(op.f('ix_ai_suggestions_run_id'), 'ai_suggestions', ['run_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_subject_type'), 'ai_suggestions', ['subject_type'], unique=False)
    op.create_table('boqs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('from_run_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','in_review','reviewed','approved','stale_approved','exported')", name=op.f('ck_boqs_boq_status_ck')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_boqs_approved_by_users')),
    sa.ForeignKeyConstraint(['from_run_id'], ['measurement_runs.id'], name=op.f('fk_boqs_from_run_id_measurement_runs')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_boqs_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boqs'))
    )
    op.create_index(op.f('ix_boqs_project_id'), 'boqs', ['project_id'], unique=False)
    op.create_table('drawing_sheets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drawing_file_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('sheet_type', sa.String(length=20), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['drawing_file_id'], ['drawing_files.id'], name=op.f('fk_drawing_sheets_drawing_file_id_drawing_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drawing_sheets')),
    sa.UniqueConstraint('drawing_file_id', 'page_number', name=op.f('uq_drawing_sheets_drawing_file_id'))
    )
    op.create_index(op.f('ix_drawing_sheets_drawing_file_id'), 'drawing_sheets', ['drawing_file_id'], unique=False)
    op.create_table('boq_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('boq_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boq_id'], ['boqs.id'], name=op.f('fk_boq_sections_boq_id_boqs')),
    sa.ForeignKeyConstraint(['parent_id'], ['boq_sections.id'], name=op.f('fk_boq_sections_parent_id_boq_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boq_sections'))
    )
    op.create_index(op.f('ix_boq_sections_boq_id'), 'boq_sections', ['boq_id'], unique=False)
    op.create_table('elements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('storey_id', sa.Uuid(), nullable=True),
    sa.Column('element_type', sa.String(length=40), nullable=False),
    sa.Column('type_source', sa.String(length=24), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ai_model', sa.String(length=60), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['measurement_runs.id'], name=op.f('fk_elements_run_id_measurement_runs')),
    sa.ForeignKeyConstraint(['sheet_id'], ['drawing_sheets.id'], name=op.f('fk_elements_sheet_id_drawing_sheets')),
    sa.ForeignKeyConstraint(['storey_id'], ['storeys.id'], name=op.f('fk_elements_storey_id_storeys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_elements'))
    )
    op.create_index(op.f('ix_elements_run_id'), 'elements', ['run_id'], unique=False)
    op.create_index(op.f('ix_elements_sheet_id'), 'elements', ['sheet_id'], unique=False)
    op.create_table('export_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('boq_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=12), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boq_id'], ['boqs.id'], name=op.f('fk_export_artifacts_boq_id_boqs')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_export_artifacts_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_artifacts'))
    )
    op.create_index(op.f('ix_export_artifacts_boq_id'), 'export_artifacts', ['boq_id'], unique=False)
    op.create_table('scale_calibrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('units_per_drawing_unit', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_scale_calibrations_confirmed_by_users')),
    sa.ForeignKeyConstraint(['sheet_id'], ['drawing_sheets.id'], name=op.f('fk_scale_calibrations_sheet_id_drawing_sheets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scale_calibrations'))
    )
    op.create_index(op.f('ix_scale_calibrations_sheet_id'), 'scale_calibrations', ['sheet_id'], unique=False)
    op.create_table('boq_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('catalogue_item_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rate_minor', sa.Integer(), nullable=True),
    sa.Column('rate_scope', sa.String(length=10), nullable=True),
    sa.Column('markup_bp', sa.Integer(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=True),
    sa.Column('measurement_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("origin IN ('mapped','manual','pc_sum')", name=op.f('ck_boq_items_boq_item_origin_ck')),
    sa.ForeignKeyConstraint(['catalogue_item_id'], ['catalogue_items.id'], name=op.f('fk_boq_items_catalogue_item_id_catalogue_items')),
    sa.ForeignKeyConstraint(['section_id'], ['boq_sections.id'], name=op.f('fk_boq_items_section_id_boq_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boq_items'))
    )
    op.create_index(op.f('ix_boq_items_section_id'), 'boq_items', ['section_id'], unique=False)
    op.create_table('geometries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('element_id', sa.Uuid(), nullable=False),
    sa.Column('geom_type', sa.String(length=16), nullable=False),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('source_handles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('derived_from', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], name=op.f('fk_geometries_element_id_elements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geometries'))
    )
    op.create_index(op.f('ix_geometries_element_id'), 'geometries', ['element_id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('element_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_type', sa.String(length=12), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=8), nullable=True),
    sa.Column('rule_id', sa.String(length=80), nullable=True),
    sa.Column('engine_version', sa.String(length=20), nullable=True),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inputs_digest', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('correction_of', sa.Uuid(), nullable=True),
    sa.Column('corrected_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('measured','measured_zero','needs_review','not_measurable','blocked')", name=op.f('ck_measurements_meas_state_ck')),
    sa.ForeignKeyConstraint(['correction_of'], ['measurements.id'], name=op.f('fk_measurements_correction_of_measurements')),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], name=op.f('fk_measurements_element_id_elements')),
    sa.ForeignKeyConstraint(['run_id'], ['measurement_runs.id'], name=op.f('fk_measurements_run_id_measurement_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measurements'))
    )
    op.create_index(op.f('ix_measurements_element_id'), 'measurements', ['element_id'], unique=False)
    op.create_index(op.f('ix_measurements_run_id'), 'measurements', ['run_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('measurement_id', sa.Uuid(), nullable=True),
    sa.Column('element_id', sa.Uuid(), nullable=True),
    sa.Column('sheet_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('blocking','review','info')", name=op.f('ck_exceptions_exc_severity_ck')),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], name=op.f('fk_exceptions_element_id_elements')),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], name=op.f('fk_exceptions_measurement_id_measurements')),
    sa.ForeignKeyConstraint(['run_id'], ['measurement_runs.id'], name=op.f('fk_exceptions_run_id_measurement_runs')),
    sa.ForeignKeyConstraint(['sheet_id'], ['drawing_sheets.id'], name=op.f('fk_exceptions_sheet_id_drawing_sheets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exceptions'))
    )
    op.create_index(op.f('ix_exceptions_element_id'), 'exceptions', ['element_id'], unique=False)
    op.create_index(op.f('ix_exceptions_measurement_id'), 'exceptions', ['measurement_id'], unique=False)
    op.create_index(op.f('ix_exceptions_run_id'), 'exceptions', ['run_id'], unique=False)
    op.create_index('ix_exceptions_run_severity', 'exceptions', ['run_id', 'severity'], unique=False)
    op.create_index(op.f('ix_exceptions_sheet_id'), 'exceptions', ['sheet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exceptions_sheet_id'), table_name='exceptions')
    op.drop_index('ix_exceptions_run_severity', table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_run_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_measurement_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_element_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_measurements_run_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_element_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_geometries_element_id'), table_name='geometries')
    op.drop_table('geometries')
    op.drop_index(op.f('ix_boq_items_section_id'), table_name='boq_items')
    op.drop_table('boq_items')
    op.drop_index(op.f('ix_scale_calibrations_sheet_id'), table_name='scale_calibrations')
    op.drop_table('scale_calibrations')
    op.drop_index(op.f('ix_export_artifacts_boq_id'), table_name='export_artifacts')
    op.drop_table('export_artifacts')
    op.drop_index(op.f('ix_elements_sheet_id'), table_name='elements')
    op.drop_index(op.f('ix_elements_run_id'), table_name='elements')
    op.drop_table('elements')
    op.drop_index(op.f('ix_boq_sections_boq_id'), table_name='boq_sections')
    op.drop_table('boq_sections')
    op.drop_index(op.f('ix_drawing_sheets_drawing_file_id'), table_name='drawing_sheets')
    op.drop_table('drawing_sheets')
    op.drop_index(op.f('ix_boqs_project_id'), table_name='boqs')
    op.drop_table('boqs')
    op.drop_index(op.f('ix_ai_suggestions_subject_type'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_run_id'), table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    op.drop_table('storeys')
    op.drop_index(op.f('ix_measurement_runs_project_id'), table_name='measurement_runs')
    op.drop_table('measurement_runs')
    op.drop_index(op.f('ix_drawing_files_sha256'), table_name='drawing_files')
    op.drop_index(op.f('ix_drawing_files_project_id'), table_name='drawing_files')
    op.drop_table('drawing_files')
    op.drop_index(op.f('ix_rates_catalogue_item_id'), table_name='rates')
    op.drop_table('rates')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_evidence_subject', table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_subject_id'), table_name='evidence_links')
    op.drop_table('evidence_links')
    op.drop_index(op.f('ix_catalogue_items_region_code'), table_name='catalogue_items')
    op.drop_table('catalogue_items')
    op.drop_index(op.f('ix_audit_log_subject_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
