"""Fixture generator for Round-3 DXF tests — real files, generated by ezdxf.

Run:  .venv/bin/python tests/fixtures/generate_dxf_fixtures.py
Writes into tests/fixtures/dxf/ (gitignored are only generated-by-us outputs;
the generated fixtures ARE committed so CI never depends on network/ezdxf
version for byte-stability of inputs).

Vertical-slice fixture: wall_plan.dxf — a simple rectangle building outline
drawn as parallel LINE pairs (two walls), $INSUNITS=4 (mm).
"""
from __future__ import annotations

from pathlib import Path

import ezdxf

OUT = Path(__file__).parent / "dxf"


def _wall_pair(msp: object, x0: float, y0: float, x1: float, y1: float, t: float) -> None:
    """One wall segment drawn as two parallel lines (a wall 'pair')."""
    dx, dy = x1 - x0, y1 - y0
    length = (dx * dx + dy * dy) ** 0.5
    # unit normal
    nx, ny = -dy / length, dx / length
    a0 = (x0 + nx * t / 2, y0 + ny * t / 2)
    a1 = (x1 + nx * t / 2, y1 + ny * t / 2)
    b0 = (x0 - nx * t / 2, y0 - ny * t / 2)
    b1 = (x1 - nx * t / 2, y1 - ny * t / 2)
    msp.add_line(a0, a1, dxfattribs={"layer": "WALL"})
    msp.add_line(b0, b1, dxfattribs={"layer": "WALL"})


def build_wall_plan() -> bytes:
    """A 6000x4000 mm rectangle: two walls (horizontal pair + vertical pair)."""
    doc = ezdxf.new("R2010")
    doc.header["$INSUNITS"] = 4  # mm
    if "WALL" not in doc.layers:
        doc.layers.add("WALL")
    msp = doc.modelspace()
    t = 200.0  # 200mm wall thickness
    # Wall A: bottom wall from (0,0) to (6000,0) as a parallel pair
    _wall_pair(msp, 0, 0, 6000, 0, t)
    # Wall B: left wall from (0,0) to (0,4000)
    _wall_pair(msp, 0, 0, 0, 4000, t)
    return _export(doc)


def _export(doc: ezdxf.document.Drawing) -> bytes:
    from io import StringIO

    buf = StringIO()
    doc.write(buf)  # ascii DXF
    return buf.getvalue().encode("ascii")


def build_no_units() -> bytes:
    """Same wall geometry but $INSUNITS absent → scale must be PROPOSED-unknown."""
    doc = ezdxf.new("R2010")
    del doc.header["$INSUNITS"]
    if "WALL" not in doc.layers:
        doc.layers.add("WALL")
    msp = doc.modelspace()
    t = 200.0
    _wall_pair(msp, 0, 0, 6000, 0, t)
    return _export(doc)


def build_open_polyline() -> bytes:
    """An open polyline asked-for-area case → OPEN_POLYLINE exception fixture."""
    doc = ezdxf.new("R2010")
    doc.header["$INSUNITS"] = 4
    msp = doc.modelspace()
    msp.add_lwpolyline([(0, 0), (1000, 0), (1000, 500)], format="xy", close=False)
    return _export(doc)


def build_self_intersecting() -> bytes:
    """A bowtie polygon → SELF_INTERSECTING refusal fixture."""
    doc = ezdxf.new("R2010")
    doc.header["$INSUNITS"] = 4
    msp = doc.modelspace()
    msp.add_lwpolyline(
        [(0, 0), (1000, 1000), (1000, 0), (0, 1000)], format="xy", close=True
    )
    return _export(doc)


def build_corrupt() -> bytes:
    """Truncated DXF — parse must fail loudly, never half-parse."""
    good = build_wall_plan()
    return good[: len(good) // 2]


def build_paperspace_only() -> bytes:
    """Geometry only in a paper-space layout → sheet not measurable."""
    doc = ezdxf.new("R2010", setup=True)
    doc.header["$INSUNITS"] = 4
    ps = doc.layouts.get("Layout1")
    t = 200.0
    dx, dy = 6000.0, 0.0
    nx, ny = 0.0, 1.0
    a0 = (0 + nx * t / 2, 0 + ny * t / 2)
    a1 = (dx + nx * t / 2, dy + ny * t / 2)
    b0 = (0 - nx * t / 2, 0 - ny * t / 2)
    b1 = (dx - nx * t / 2, dy - ny * t / 2)
    ps.add_line(a0, a1, dxfattribs={"layer": "WALL"})
    ps.add_line(b0, b1, dxfattribs={"layer": "WALL"})
    return _export(doc)


def build_block_fixture() -> bytes:
    """A wall drawn inside a block + INSERT reference → explosion with handle chain."""
    doc = ezdxf.new("R2010")
    doc.header["$INSUNITS"] = 4
    if "WALL" not in doc.layers:
        doc.layers.add("WALL")
    block = doc.blocks.new("WALLSEG")
    block.add_line((-3000, 100), (3000, 100), dxfattribs={"layer": "WALL"})
    block.add_line((-3000, -100), (3000, -100), dxfattribs={"layer": "WALL"})
    msp = doc.modelspace()
    msp.add_blockref("WALLSEG", insert=(0, 0))
    return _export(doc)


FIXTURES: dict[str, object] = {
    "wall_plan.dxf": build_wall_plan,
    "no_units.dxf": build_no_units,
    "open_polyline.dxf": build_open_polyline,
    "self_intersecting.dxf": build_self_intersecting,
    "corrupt.dxf": build_corrupt,
    "paperspace_only.dxf": build_paperspace_only,
    "block_wall.dxf": build_block_fixture,
}


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, build in FIXTURES.items():
        path = OUT / name
        path.write_bytes(build())
        print(f"wrote {path} ({path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
